AWSTemplateFormatVersion: '2010-09-09'
Description: RDS DB Instance with subnet group

Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  DBUsername:
    Type: String
    Default: admin
  DBName:
    Type: String
    Default: finalproject
    Description: Initial DB name (will be created by RDS)
  DBSecretArn:
    Type: String
  RDSSecurityGroup:
    Type: String
  # CloudTrailArn:
  #   Type: String
  AppName:
    Type: String
  Environment:
    Type: String

Resources:
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${AppName}-${Environment}-rds-subnetgroup"
      DBSubnetGroupDescription: !Sub "RDS subnet group for ${AppName}-${Environment}"
      SubnetIds: !Ref SubnetIds

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${AppName}-${Environment}-rds-dbinstance"
      DBName: !Ref DBName
      Engine: mysql
      EngineVersion: "8.0"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp3
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "01:00-02:00"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecretArn}:SecretString:password}}'
      EnableCloudwatchLogsExports:
        - error
        - general
        - slowquery
      Tags:
        - Key: AppName
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment

  # RDSCloudTrailAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmName: !Sub "${AppName}-${Environment}-rds-cloudwatch-alarm"
  #     AlarmDescription: "Alert on unauthorized RDS actions (auditing via CloudTrail)"
  #     MetricName: EventCount
  #     Namespace: AWS/CloudTrail
  #     Statistic: Sum
  #     Period: 300
  #     EvaluationPeriods: 1
  #     Threshold: 0
  #     ComparisonOperator: GreaterThanThreshold
  #     TreatMissingData: notBreaching
  #     Dimensions:
  #       - Name: TrailARN
  #         Value: !Ref CloudTrailArn
  #     AlarmActions: []  # You can pass SNS topic ARN from parent stack here if required

Outputs:
  RdsEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
  RdsPort:
    Description: "RDS endpoint port"
    Value: !GetAtt DBInstance.Endpoint.Port
  DbName:
    Description: "Database name"
    Value: !Ref DBName
  RDSInstanceIdentifier:
    Description: Identifier of the RDS DB instance
    Value: !Ref DBInstance
